### ISSUE TITLE
how to compile and run?

### ISSUE THREAD

**Issue by benkoshy** [woldena/minesweep#3]
Hi Andre

This looks quite interesting.

I've cloned the repo and am trying to run it on my PC.

I've fired up the elm reactor and have clicked on `Main.elm` and `index.html` but nothing seems to work straight away.

when i click on `Main.elm` from the reactor it is giving me this error:

> Initialization Error
> Error: Problem with the flags given to your Elm program on initialization.
> Problem with the given value:
> undefined
> Expecting an INT

If you have any ideas on how to get this started up please do let me know.

regards

Ben

**Comment by okkero** [comment]
Run it with `npm run start` or `yarn start`

**Comment by benkoshy** [comment]
chrs, but couldn't get it working.

i'll have to look into it more closely.

**Comment by andre-wolden** [comment]
Hi,

Sorry for the extremely late reply. okkero is right, that is the way to run it. And if you want to build it you can run `npm run build` or `npm run prod`. The repo is based on the awesome repo https://github.com/simonh1000/elm-webpack-starter.

Let me know if you still don't get it to run.
